apiVersion: v1
kind: Service
metadata:
  name: {{ include "infini-connect-ui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infini-connect-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: {{ .Values.service.ports.http.protocol }}
      name: http
    - port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      protocol: {{ .Values.service.ports.https.protocol }}
      name: https
  selector:
    {{- include "infini-connect-ui.selectorLabels" . | nindent 4 }}
